name: CBA Config Linter

on:
  pull_request_target:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Run CBA Config Linter
      id: linter
      run: |
        python -m pip install --upgrade pip
        python scripts/cba_linter.py configs/
        
    - name: Create review comment
      if: always() && github.event_name == 'pull_request_target'
      uses: actions/github-script@v6
      with:
        script: |
          const output = await github.rest.issues.listCommentsForRepo({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
          });
          
          const existingComment = output.data.find(comment => comment.user.login === 'github-actions[bot]' && comment.body.includes('CBA Linter Results'));
          
          const lintResults = `${{ steps.linter.outputs.result }}`;
          const commentBody = `### CBA Linter Results\n\n${lintResults}`;
          
          if (existingComment) {
            await github.rest.issues.updateComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: existingComment.id,
              body: commentBody
            });
          } else {
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: commentBody
            });
          }
