//------------------------------------------------------------------
//------------------------------------------------------------------
//
//						Waffen
//
//------------------------------------------------------------------
//------------------------------------------------------------------
[
	"CUP_arifle_G36A_RIS",
	"CUP_arifle_G36A_RIS_camo",
	"CUP_arifle_G36A_RIS_wdl",
	"CUP_arifle_G36A3",
	"CUP_arifle_G36A3_camo",
	"CUP_arifle_G36A3_wdl",
	"CUP_arifle_G36K_RIS",
	"CUP_arifle_G36K_RIS_camo",
	"CUP_arifle_G36K_RIS_wdl",
	"CUP_arifle_G36KA3",
	"CUP_arifle_G36KA3_afg_camo",
	"CUP_arifle_G36KA3_afg_wdl",
	"CUP_arifle_G36C",
	"CUP_arifle_G36C_camo",
	"CUP_arifle_G36C_wdl",
	"CUP_arifle_G36CA3",
	"CUP_arifle_G36CA3_camo",
	"CUP_arifle_G36CA3_wdl",
	"CUP_arifle_AG36",
	"CUP_arifle_G36A_AG36_RIS_camo",
	"CUP_arifle_G36A_AG36_RIS_wdl",
	"CUP_arifle_G36A3_AG36",
	"CUP_arifle_G36A3_AG36_camo",
	"CUP_arifle_G36A3_AG36_wdl",
	"CUP_arifle_HK416_Black",
	"CUP_arifle_HK416_Desert",
	"CUP_arifle_HK416_Wood",
	"CUP_arifle_HK416_CQB_Black",
	"CUP_arifle_HK416_CQB_Desert",
	"CUP_arifle_HK416_CQB_Wood",
	"CUP_arifle_HK416_CQB_AG36",
	"CUP_arifle_HK416_CQB_AG36_Desert",
	"CUP_arifle_HK416_CQB_AG36_Wood",
	"CUP_arifle_HK416_AGL_Black",
	"CUP_arifle_HK416_AGL_Desert",
	"CUP_arifle_HK416_AGL_Wood",
	"CUP_arifle_HK417_12",
	"CUP_arifle_HK417_12_Desert",
	"CUP_arifle_HK417_12_Wood",
	"CUP_arifle_HK417_12_AG36",
	"CUP_arifle_HK417_12_AG36_Desert",
	"CUP_arifle_HK417_12_AG36_Wood",	
//------------------------------------------------------------------
//------------------------------------------------------------------
//
//						Visiere
//
//------------------------------------------------------------------
//------------------------------------------------------------------
	"CUP_optic_MicroT1",
	"CUP_optic_MicroT1_coyote",
	"CUP_optic_MicroT1_OD",
	"CUP_optic_AC11704_Black",
	"CUP_optic_AC11704_Tan",
	"CUP_optic_AC11704_OD",
	"CUP_optic_Elcan_SpecterDR_RMR_black",
	"CUP_optic_Elcan_SpecterDR_RMR",
	"CUP_optic_Elcan_SpecterDR_RMR_od",
	"CUP_optic_Elcan_SpecterDR_KF_RMR_black",
	"CUP_optic_Elcan_SpecterDR_KF_RMR",
	"CUP_optic_Elcan_SpecterDR_KF_RMR_od",
	"CUP_optic_Elcan_reflex",
	"CUP_optic_Elcan_reflex_Coyote",
	"CUP_optic_Elcan_reflex_OD",
	"CUP_optic_HoloBlack",
	"CUP_optic_HoloDesert",
	"CUP_optic_HoloWdl",
	"CUP_optic_Eotech553_Black",
	"CUP_optic_Eotech533",
	"CUP_optic_Eotech553_OD",
	"CUP_optic_G33_HWS_BLK",
	"CUP_optic_G33_HWS_TAN",
	"CUP_optic_G33_HWS_OD",
	"optic_Holosight_blk_F",
	"optic_Holosight",
	"optic_Holosight_lush_F",
	"optic_Holosight_smg_blk_F",
	"optic_Holosight_smg",
	"optic_Holosight_smg_khk_F",
	"CUP_optic_HensoldtZO_low",
	"CUP_optic_HensoldtZO_low_desert",
	"CUP_optic_HensoldtZO_low_od",
	"CUP_optic_HensoldtZO_low_RDS",
	"CUP_optic_HensoldtZO_low_RDS_desert",
	"CUP_optic_HensoldtZO_low_RDS_od",		
	"CUP_optic_ZeissZPoint",
	"CUP_optic_ZeissZPoint_desert",
	"CUP_optic_ZeissZPoint_wood",
//------------------------------------------------------------------
//------------------------------------------------------------------
//
//						Pointer
//
//------------------------------------------------------------------
//------------------------------------------------------------------
	"CUP_acc_ANPEQ_15_Flashlight_Black_L",
	"CUP_acc_ANPEQ_15_Flashlight_Tan_L",
	"CUP_acc_ANPEQ_15_Flashlight_OD_L",
	"CUP_acc_LLM01_L",
	"CUP_acc_LLM01_desert_L",
	"CUP_acc_LLM01_od_L",
	"CUP_acc_LLM_black",
	"CUP_acc_LLM",
	"CUP_acc_LLM_od",
//------------------------------------------------------------------
//------------------------------------------------------------------
//
//						Bipods
//
//------------------------------------------------------------------
//------------------------------------------------------------------
	"CUP_bipod_Harris_1A2_L_BLK",
	"CUP_Bipod_G36",
//------------------------------------------------------------------
//------------------------------------------------------------------
//
//						Secondarys
//
//------------------------------------------------------------------
//------------------------------------------------------------------
	"CUP_hgun_M17_Black",
	"ACE_VMH3",
//------------------------------------------------------------------
//------------------------------------------------------------------
//
//						Launcher
//
//------------------------------------------------------------------
//------------------------------------------------------------------
	"CUP_launch_HCPF3",
	"CUP_launch_M72A6",
//------------------------------------------------------------------
//------------------------------------------------------------------
//
//						Uniforms
//
//------------------------------------------------------------------
//------------------------------------------------------------------
	"CUP_U_B_GER_Flecktarn_1",
	"CUP_U_B_GER_Tropentarn_1",
	"CUP_U_B_GER_Flecktarn_4",
	"CUP_U_B_GER_Tropentarn_4",
	"CUP_U_B_GER_Flecktarn_2",
	"CUP_U_B_GER_Tropentarn_2",
	"CUP_U_B_GER_Flecktarn_3",
	"CUP_U_B_GER_Tropentarn_3",
	"CUP_U_B_GER_Flecktarn_5",
	"CUP_U_B_GER_Tropentarn_5",
	"CUP_U_B_GER_Flecktarn_8",
	"CUP_U_B_GER_Tropentarn_8",
	"CUP_U_B_GER_Flecktarn_6",
	"CUP_U_B_GER_Tropentarn_6",
	"CUP_U_B_GER_Flecktarn_7",
	"CUP_U_B_GER_Tropentarn_7",
	"CUP_U_B_GER_Fleck_Crye",
	"CUP_U_B_GER_Fleck_Crye2",
	"CUP_U_B_GER_Crye",
	"CUP_U_B_GER_Crye2",
//------------------------------------------------------------------
//------------------------------------------------------------------
//
//						Vests
//
//------------------------------------------------------------------
//------------------------------------------------------------------
	"CUP_V_B_GER_PVest_Fleck_TL",
	"CUP_V_B_GER_PVest_Trop_TL",
	"CUP_V_B_GER_PVest_Fleck_TL_LT",
	"CUP_V_B_GER_PVest_Trop_TL_LT",
	"GRE_PlateCarrier1_Flecktarn",
	"GRE_PlateCarrier1_Tropentarn",
	"V_Chestrig_rgr",
//------------------------------------------------------------------
//------------------------------------------------------------------
//
//						Backpacks
//
//------------------------------------------------------------------
//------------------------------------------------------------------
	"TFAR_mr3000_bwmod",
	"TFAR_rt1523g_big_bwmod_tropen",
	"TFAR_rt1523g_bwmod",
	"TFAR_rt1523g_rhs",
//------------------------------------------------------------------
//------------------------------------------------------------------
//
//						Helme
//
//------------------------------------------------------------------
//------------------------------------------------------------------
	"CUP_H_Ger_M92_Cover",
	"CUP_H_Ger_M92_Cover_Trop",
	"CUP_H_OpsCore_Covered_Fleck",
	"CUP_H_OpsCore_Covered_Tropen",
	"CUP_H_OpsCore_Covered_Tropen_NoHS",
	"CUP_H_OpsCore_Covered_Tropen_NoHS",
	"CUP_H_OpsCore_Covered_Fleck_SF",
	"CUP_H_OpsCore_Covered_Tropen_SF",
//------------------------------------------------------------------
//------------------------------------------------------------------
//
//						Goggles
//
//------------------------------------------------------------------
//------------------------------------------------------------------
	"G_Aviator",
	"G_Bandanna_aviator",
	"G_Bandanna_oli",
	"G_Bandanna_khk",
	"G_Bandanna_oli",
	"G_Bandanna_shades",
	"G_Bandanna_tan",
	"CUP_G_ESS_BLK_Dark",
	"CUP_G_ESS_BLK",
	"CUP_G_ESS_BLK_Facewrap_Black",
	"CUP_G_ESS_KHK_Facewrap_Tan",
	"CUP_G_ESS_RGR_Facewrap_Tropical",
	"CUP_G_ESS_BLK_Scarf_Blk",
	"CUP_G_ESS_BLK_Scarf_Grn",
	"CUP_G_ESS_KHK_Scarf_Tan",
	"CUP_G_ESS_BLK_Scarf_Face_Blk",
	"CUP_G_ESS_BLK_Scarf_Face_Grn",
	"CUP_G_ESS_KHK_Scarf_Face_Tan",
	"CUP_PMC_Facewrap_Black",
	"CUP_PMC_Facewrap_Tan",
	"CUP_PMC_Facewrap_Tropical",
	"CUP_G_PMC_Facewrap_Black_Glasses_Dark",
	"CUP_G_PMC_Facewrap_Tan_Glasses_Dark",
	"CUP_G_PMC_Facewrap_Tropical_Glasses_Dark",
	"CUP_G_Scarf_Face_Grn",
	"CUP_G_Scarf_Face_Blk",
	"CUP_G_Scarf_Face_Grn",
	"CUP_G_Scarf_Face_Tan",
	"CUP_G_Oakleys_Drk",
	"CUP_G_Grn_Scarf_Shades",
	"CUP_G_Tan_Scarf_Shades",
	"G_Shades_Black",
	"G_Squares_Tinted",
	"CUP_FR_NeckScarf3",
	"CUP_FR_NeckScarf",
	"CUP_FR_NeckScarf2",
	"G_Squares",
	"kat_mask_M04",
	"kat_mask_M50",
//------------------------------------------------------------------
//------------------------------------------------------------------
//
//						NVGs
//
//------------------------------------------------------------------
//------------------------------------------------------------------
	"CUP_NVG_PVS7",
	"CUP_NVG_PVS15_black",
	"CUP_NVG_PVS15_black_WP",
//------------------------------------------------------------------
//------------------------------------------------------------------
//
//						Binoculars
//
//------------------------------------------------------------------
//------------------------------------------------------------------
	"Binocular",
	"Rangefinder",
	"Laserdesignator_02_ghex_F",
	"ACE_Vector",
//------------------------------------------------------------------
//------------------------------------------------------------------
//
//						Items
//
//------------------------------------------------------------------
//------------------------------------------------------------------
	"ItemMap",
	
	"ItemAndroid",
	"ItemcTab",
	"ItemMicroDAGR",
	"ItemGPS",

	"TFAR_anprc152",

	"ItemCompass",

	"ItemWatch",
	"ACE_Altimeter",
//------------------------------------------------------------------
//------------------------------------------------------------------
//
//						Magazines
//
//------------------------------------------------------------------
//------------------------------------------------------------------
	"CUP_30Rnd_556x45_G36",
	"CUP_30Rnd_556x45_G36_camo",
	"CUP_30Rnd_556x45_G36_wdl",
	"CUP_30Rnd_TE1_Red_Tracer_556x45_G36",
	"CUP_30Rnd_TE1_Red_Tracer_556x45_G36_camo",
	"CUP_30Rnd_TE1_Red_Tracer_556x45_G36_wdl",
	"CUP_30Rnd_556x45_PMAG_BLACK",
	"CUP_30Rnd_556x45_PMAG_COYOTE",
	"CUP_30Rnd_556x45_PMAG_OD",
	"CUP_30Rnd_556x45_PMAG_BLACK_Tracer_Red",
	"CUP_30Rnd_556x45_PMAG_COYOTE_Tracer_Red",
	"CUP_30Rnd_556x45_PMAG_OD_Tracer_Red",
	"CUP_20Rnd_762x51_HK417",
	"CUP_20Rnd_762x51_HK417_Camo_Desert",
	"CUP_20Rnd_762x51_HK417_Camo_Wood",
	"CUP_20Rnd_TE1_Red_Tracer_762x51_HK417",
	"CUP_17Rnd_9x19_M17_Black",
	"CUP_21Rnd_9x19_M17_Black",
	"CUP_1Rnd_HE_M203",
	"CUP_1Rnd_HEDP_M203",
	"UGL_FlareWhite_F",
	"UGL_FlareGreen_F",
	"UGL_FlareRed_F",
	"UGL_FlareCIR_F",
	"CUP_1Rnd_StarCluster_Red_M203",
	"1Rnd_SmokeRed_Grenade_shell",
	"1Rnd_SmokeGreen_Grenade_shell",
	"1Rnd_Smoke_Grenade_shell",
//------------------------------------------------------------------
//------------------------------------------------------------------
//
//						Grenades / Throw
//
//------------------------------------------------------------------
//------------------------------------------------------------------
	"SmokeShell",
	"SmokeShellGreen",
	"SmokeShellRed",
	"SmokeShellPurple",
	"SmokeShellOrange",
	"SmokeShellBlue",
	"CUP_HandGrenade_M67",
	"Chemlight_blue",
	"ACE_Chemlight_HiBlue",
	"Chemlight_green",
	"ACE_Chemlight_HiGreen",
	"ACE_Chemlight_IR",
	"ACE_Chemlight_Orange",
	"ACE_Chemlight_UltraHiOrange",
	"ACE_Chemlight_White",
	"ACE_Chemlight_HiWhite",
	"ACE_Chemlight_HiYellow",
	"Chemlight_red",
	"ACE_Chemlight_HiRed",
	"B_IR_Grenade",
	"ACE_HandFlare_Red",
	"ACE_HandFlare_Green",
//------------------------------------------------------------------
//------------------------------------------------------------------
//
//						Explosives / Put
//
//------------------------------------------------------------------
//------------------------------------------------------------------
	"DemoCharge_Remote_Mag",
//------------------------------------------------------------------
//------------------------------------------------------------------
//
//						Medical
//
//------------------------------------------------------------------
//------------------------------------------------------------------
	"ACE_adenosine",
	"ACE_fieldDressing",
	"ACE_elasticBandage",
	"ACE_packingBandage",
	"ACE_quikclot",
	"ACE_morphine",
	"ACE_salineIV_500",
	"ACE_salineIV",
	"ACE_splint",
	"ACE_tourniquet",
	"kat_chestSeal",
//------------------------------------------------------------------
//------------------------------------------------------------------
//
//						Misc 1
//
//------------------------------------------------------------------
//------------------------------------------------------------------
	"ACE_EntrenchingTool",
	"ACE_Flashlight_XL50",
	"ACE_MapTools",
	"ACE_wirecutter",
	"ACE_M26_Clacker",
//------------------------------------------------------------------
//------------------------------------------------------------------
//
//						Misc 2
//
//------------------------------------------------------------------
//------------------------------------------------------------------
	"ACE_CableTie",
	"ACE_EarPlugs",
	"ACE_IR_Strobe_Item",
	"ACE_SpraypaintBlack",
	"ACE_SpraypaintBlue",
	"ACE_SpraypaintGreen",
	"ACE_SpraypaintRed",
	"ACE_SpraypaintWhite",
	"ACE_SpraypaintYellow",
	"ItemcTabHCam",
	"ItemMicroDAGRMisc"
];