//------------------------------------------------------------------
//------------------------------------------------------------------
//
//						Waffen
//
//------------------------------------------------------------------
//------------------------------------------------------------------
[
	"CUP_arifle_AG36",
	"CUP_arifle_G36A_AG36_RIS_camo",
	"CUP_arifle_G36A_AG36_RIS_wdl",
	"CUP_arifle_G36A3_AG36",
	"CUP_arifle_G36A3_AG36_camo",
	"CUP_arifle_G36A3_AG36_wdl",
	"CUP_arifle_HK416_CQB_AG36",
	"CUP_arifle_HK416_CQB_AG36_Desert",
	"CUP_arifle_HK416_CQB_AG36_Wood",
	"CUP_arifle_HK416_AGL_Black",
	"CUP_arifle_HK416_AGL_Desert",
	"CUP_arifle_HK416_AGL_Wood",
	"CUP_arifle_HK417_12_AG36",
	"CUP_arifle_HK417_12_AG36_Desert",
	"CUP_arifle_HK417_12_AG36_Wood",
	"CUP_arifle_HK417_20",
	"CUP_arifle_HK417_20_Desert",
	"CUP_arifle_HK417_20_Wood",
	"arifle_SPAR_03_blk_F",
	"arifle_SPAR_03_snd_F",
	"arifle_SPAR_03_khk_F",
	"CUP_lmg_minimi_railed",
	"CUP_arifle_MG36",
	"CUP_arifle_MG36_camo",
	"CUP_arifle_MG36_wdl",
	"LMG_03_F",
	"CUP_lmg_MG3_rail",
	"CUP_lmg_Mk48_nohg",
	"MMG_01_tan_F",
	"MMG_02_black_F",
	"CUP_srifle_G22_wdl",
	"CUP_srifle_G22_blk",
	"CUP_srifle_G22_des",
	"srifle_GM6_F",
	"CUP_srifle_M107_Base",
	"CUP_smg_MP5A5",
	"SMG_05_F",
	"CUP_smg_MP7",
//------------------------------------------------------------------
//------------------------------------------------------------------
//
//						Visiere
//
//------------------------------------------------------------------
//------------------------------------------------------------------
	"CUP_optic_LeupoldMk4_25x50_LRT",
	"CUP_optic_LeupoldMk4_25x50_LRT_DESERT",
	"CUP_optic_LeupoldMk4_25x50_LRT_WOODLAND",
	"CUP_optic_Leupold_VX3",
	"optic_LRPS",
	"CUP_optic_AN_PVS_10_black",
	"CUP_optic_AN_PVS_10_black",
	"CUP_optic_AN_PVS_10_od",
	"optic_AMS",
	"optic_AMS_snd",
	"optic_AMS_khk",
	"CUP_optic_SMAW_Scope",
//------------------------------------------------------------------
//------------------------------------------------------------------
//
//						Pointer
//
//------------------------------------------------------------------
//------------------------------------------------------------------


	
//------------------------------------------------------------------
//------------------------------------------------------------------
//
//						Muzzle
//
//------------------------------------------------------------------
//------------------------------------------------------------------

"muzzle_antenna_02_f",
"muzzle_antenna_03_f",
"muzzle_antenna_01_f",

//------------------------------------------------------------------
//------------------------------------------------------------------
//
//						Bipods
//
//------------------------------------------------------------------
//------------------------------------------------------------------



//------------------------------------------------------------------
//------------------------------------------------------------------
//
//						Secondarys
//
//------------------------------------------------------------------
//------------------------------------------------------------------
	"ACE_Flashlight_Maglite_ML300L",
	"CUP_hgun_FlareGun",
	"hgun_esd_01_F",
//------------------------------------------------------------------
//------------------------------------------------------------------
//
//						Launcher
//
//------------------------------------------------------------------
//------------------------------------------------------------------
	"CUP_launch_BF3",
	"CUP_launch_PzF3",
	"CUP_launch_M72A6",
	"launch_MRAWS_green_F",
	"launch_MRAWS_sand_F",
	"launch_O_Vorona_green_F",
	"launch_O_Vorona_brown_F",
	"CUP_launch_Mk153Mod0",
	"launch_B_Titan_olive_F",
	"launch_B_Titan_F",
	"launch_I_Titan_short_F",
	"launch_B_Titan_short_F",
	"CUP_TOW2_carry",
	"ace_csw_m220CarryTripod",
	"GerRng_HMG_M2_Sh_carry",
	"GerRng_HMG_M2_ScSh_carry",
	"ace_csw_m3CarryTripod",
	"ace_csw_m3CarryTripodLow",
	"GerRng_GMG_Mk19",
	"CUP_MK19_carry",
	"CUP_m252_carry",
	"ace_csw_carryMortarBaseplate",
//------------------------------------------------------------------
//------------------------------------------------------------------
//
//						Uniforms
//
//------------------------------------------------------------------
//------------------------------------------------------------------
	"CUP_U_B_GER_Fleck_Overalls_Pilot",
	"CUP_U_B_GER_Fleck_Overalls_Tank",
	"CUP_U_B_USArmy_PilotOverall",
	"CUP_U_B_USMC_PilotOverall",
	"U_B_CBRN_Suit_01_Wdl_F",
	"U_B_CBRN_Suit_01_MTP_F",
	"U_B_FullGhillie_ard",
	"U_B_T_FullGhillie_tna_F",
	"U_B_FullGhillie_lsh",
	"U_B_FullGhillie_sard",
	"U_B_GhillieSuit",
//------------------------------------------------------------------
//------------------------------------------------------------------
//
//						Vests
//
//------------------------------------------------------------------
//------------------------------------------------------------------
	"CUP_V_B_GER_PVest_Fleck_Gren",
	"CUP_V_B_GER_PVest_Trop_Gren",
	"CUP_V_B_GER_PVest_Fleck_MG",
	"CUP_V_B_GER_PVest_Trop_MG",
	"CUP_V_B_GER_PVest_Fleck_Med",
	"CUP_V_B_GER_PVest_Trop_Med",
	"CUP_V_B_GER_PVest_Fleck_OFC",
	"CUP_V_B_GER_PVest_Trop_OFC",
	"CUP_V_B_GER_PVest_Fleck_RFL",
	"CUP_V_B_GER_PVest_Trop_RFL",
	"CUP_V_B_GER_PVest_Fleck_TL",
	"CUP_V_B_GER_PVest_Trop_TL",
	"CUP_V_B_GER_PVest_Fleck_Gren_LT",
	"CUP_V_B_GER_PVest_Trop_Gren_LT",
	"CUP_V_B_GER_PVest_Fleck_MG_LT",
	"CUP_V_B_GER_PVest_Trop_MG_LT",
	"CUP_V_B_GER_PVest_Fleck_Med_LT",
	"CUP_V_B_GER_PVest_Trop_Med_LT",
	"CUP_V_B_GER_PVest_Fleck_RFL_LT",
	"CUP_V_B_GER_PVest_Trop_RFL_LT",
	"CUP_V_B_GER_PVest_Fleck_TL_LT",
	"CUP_V_B_GER_PVest_Trop_TL_LT",
	"CUP_V_B_GER_Carrier_Vest_3",
	"V_Chestrig_rgr",
	"CUP_V_B_PilotVest",
	"Aircrew_vest_2_NH",
	"V_EOD_olive_F",
	"V_EOD_coyote_F",
	"V_PlateCarrierIAGL_oli",
	"V_Safety_yellow_F",
//------------------------------------------------------------------
//------------------------------------------------------------------
//
//						Backpacks
//
//------------------------------------------------------------------
//------------------------------------------------------------------
	"TFAR_mr3000_bwmod",
	"TFAR_rt1523g_big_bwmod_tropen",
	"TFAR_rt1523g_bwmod",
	"TFAR_rt1523g_rhs",
	"ace_gunbag",
	"ace_gunbag_Tan",
	"C_IDAP_UGV_02_Demining_backpack_F",
	"B_UGV_02_Demining_backpack_F",
	"B_UGV_02_Science_backpack_F",
	"B_UAV_01_backpack_F",
	"B_UAV_06_backpack_F",
	"C_IDAP_UAV_06_antimine_backpack_F",
	"CUP_B_Mk19_Gun_Bag",
	"CUP_B_Mk19_Tripod_Bag",
	"CUP_B_M2_Gun_Bag",
	"CUP_B_M2_MiniTripod_Bag",
	"CUP_B_M2_Tripod_Bag",
	"CUP_B_M252_Bipod_Bag",
	"CUP_B_M252_Gun_Bag",
	"CUP_B_TOW2_Tripod_Bag",
	"CUP_B_Tow_Gun_Bag",
	"CUP_B_TOW_Tripod_Bag",
	"B_CombinationUnitRespirator_01_F",
	"B_SCBA_01_F",
	"ACE_TacticalLadder_Pack",

	"tfw_ilbeMR3000_blade_flk",
	"tfw_ilbeMR3000_blade_trp",
	"tfw_ilbeRT1523_blade_flk",
	"tfw_ilbeRT1523_blade_trp",
	
	"tfw_ilbeMR3000_blade_limaflk",
	"tfw_ilbeMR3000_blade_limatrp",
	"tfw_ilbeRT1523_blade_limaflk",
	"tfw_ilbeRT1523_blade_limatrp",

	
	"tfw_ilbeMR3000_DD_flk",
	"tfw_ilbeMR3000_DD_trp",
	"tfw_ilbeRT1523_DD_flk",
	"tfw_ilbeRT1523_DD_trp",
	
	"tfw_ilbeMR3000_DD_limaflk",
	"tfw_ilbeMR3000_DD_limatrp",
	"tfw_ilbeRT1523_DD_limaflk",
	"tfw_ilbeRT1523_DD_limatrp",
	

	"tfw_ilbeMR3000_whip_flk",
	"tfw_ilbeMR3000_whip_trp",
	"tfw_ilbeRT1523_whip_flk",
	"tfw_ilbeRT1523_whip_trp",	

	"tfw_ilbeMR3000_whip_limaflk",
	"tfw_ilbeMR3000_whip_limatrp",
	"tfw_ilbeRT1523_whip_limaflk",
	"tfw_ilbeRT1523_whip_limatrp",

	
	"tfw_ilbeRT1523_blade_gr",
	"tfw_ilbeMR3000_blade_gr",
	"tfw_ilbeRT1523_blade_coy",
	"tfw_ilbeMR3000_blade_coy",
	
	"tfw_ilbeRT1523_DD_gr",
	"tfw_ilbeMR3000_DD_gr",
	"tfw_ilbeRT1523_DD_coy",
	"tfw_ilbeMR3000_DD_coy",
	
	"tfw_ilbeRT1523_whip_gr",
	"tfw_ilbeMR3000_whip_gr",
	"tfw_ilbeRT1523_whip_coy",
	"tfw_ilbeMR3000_whip_coy",
//------------------------------------------------------------------
//------------------------------------------------------------------
//
//						Helme
//
//------------------------------------------------------------------
//------------------------------------------------------------------
	"CUP_H_Ger_Boonie2_Flecktarn",
	"CUP_H_Ger_Boonie2_desert",
	"CUP_H_Ger_Cap_EP_Grn1",
	"CUP_H_Ger_Cap_EP_Tan1",
	"CUP_H_Ger_Cap_Grn2",
	"H_Construction_basic_yellow_F",
	"H_PilotHelmetFighter_B",
	"H_CrewHelmetHeli_O",
	"H_PilotHelmetHeli_O",
	"H_HelmetCrew_B",
	"H_CrewHelmetHeli_B",
	"H_PilotHelmetHeli_B",
	"H_HelmetSpecB_wdl",
	"H_HelmetSpecB_sand",
	"CUP_H_SPH4_khaki",
//------------------------------------------------------------------
//------------------------------------------------------------------
//
//						Goggles
//
//------------------------------------------------------------------
//------------------------------------------------------------------
	"G_Aviator",
	"G_Balaclava_blk",
	"G_Bandanna_aviator",
	"G_Bandanna_beast",
	"G_AirPurifyingRespirator_01_F",
	"G_RegulatorMask_F",
//------------------------------------------------------------------
//------------------------------------------------------------------
//
//						NVGs
//
//------------------------------------------------------------------
//------------------------------------------------------------------
	"CUP_NVG_GPNVG_black",
	"CUP_NVG_GPNVG_black_WP",
//------------------------------------------------------------------
//------------------------------------------------------------------
//
//						Binoculars
//
//------------------------------------------------------------------
//------------------------------------------------------------------
	"Rangefinder",
	"Laserdesignator_02_ghex_F",
	"ACE_Vector",
//------------------------------------------------------------------
//------------------------------------------------------------------
//
//						Items
//
//------------------------------------------------------------------
//------------------------------------------------------------------
	"ItemAndroid",
	"ItemcTab",
	"ItemMicroDAGR",
	"ItemGPS",
	"B_UavTerminal",
	"C_UavTerminal",

	"ChemicalDetector_01_watch_F",
	
	"tfw_blade",
	"tfw_dd",
	"tfw_whip",
//------------------------------------------------------------------
//------------------------------------------------------------------
//
//						Magazines
//
//------------------------------------------------------------------
//------------------------------------------------------------------
	"CUP_200Rnd_TE4_Red_Tracer_556x45_M249",
	"CUP_100Rnd_556x45_BetaCMag",
	"CUP_100Rnd_556x45_BetaCMag_camo",
	"CUP_100Rnd_556x45_BetaCMag_wdl",
	"CUP_100Rnd_TE1_Red_Tracer_556x45_BetaCMag",
	"CUP_100Rnd_TE1_Red_Tracer_556x45_BetaCMag_camo",
	"CUP_100Rnd_TE1_Red_Tracer_556x45_BetaCMag_wdl",
	"CUP_200Rnd_TE1_LRT4_Red_Tracer_762x51_Belt_M",
	"CUP_120Rnd_TE4_LRT4_Red_Tracer_762x51_Belt_M",
	"130Rnd_338_Mag",
	"150Rnd_93x64_Mag",
	"CUP_5Rnd_762x67_G22",
	"ACE_5Rnd_127x99_Mag",
	"ACE_5Rnd_127x99_API_Mag",
	"ACE_5Rnd_127x99_AMAX_Mag",
	"CUP_30Rnd_9x19_MP5",
	"CUP_40Rnd_46x30_MP7",
	"CUP_1Rnd_HE_M203",
	"CUP_1Rnd_HEDP_M203",
	"UGL_FlareWhite_F",
	"UGL_FlareGreen_F",
	"UGL_FlareRed_F",
	"UGL_FlareCIR_F",
	"CUP_1Rnd_StarCluster_Red_M203",
	"1Rnd_SmokeRed_Grenade_shell",
	"1Rnd_SmokeGreen_Grenade_shell",
	"1Rnd_Smoke_Grenade_shell",
	"ACE_HuntIR_M203",
	"Laserbatteries",
	"CUP_SMAW_HEAA_M",
	"CUP_SMAW_Spotting",
	"Titan_AA",
	"Titan_AT",
	"Titan_AP",
	"Vorona_HEAT",
	"Vorona_HE",
	"MRAWS_HE_F",
	"MRAWS_HEAT55_F",
	"MRAWS_HEAT_F",
	"MAA_MAAWS_ASM509",
	"MAA_MAAWS_HEDP502",
	"MAA_MAAWS_MT756",
	"MAA_MAAWS_GMM_HE",
	"MAA_MAAWS_GMM_HEAT",
	"MAA_MAAWS_GMM_MT",
	"MAA_MAAWS_ILLUM545",
	"MAA_MAAWS_SMOKE469",	
	"CUP_compats_48Rnd_40mm_MK19_M",
	"CUP_compats_TOW2_M",
	"ace_csw_100Rnd_127x99_mag",
	"ace_csw_100Rnd_127x99_mag_red",
	"ACE_1Rnd_82mm_Mo_HE",
	"ACE_1Rnd_82mm_Mo_Illum",
	"ACE_1Rnd_82mm_Mo_Smoke",
	"ACE_1Rnd_82mm_Mo_HE_LaserGuided",
//------------------------------------------------------------------
//------------------------------------------------------------------
//
//						Grenades / Throw
//
//------------------------------------------------------------------
//------------------------------------------------------------------
	"MiniGrenade",
	"B_IR_Grenade",
	"ACE_HandFlare_Red",
	"ACE_HandFlare_Green",
//------------------------------------------------------------------
//------------------------------------------------------------------
//
//						Explosives / Put
//
//------------------------------------------------------------------
//------------------------------------------------------------------
	"DemoCharge_Remote_Mag",
	"SatchelCharge_Remote_Mag",
	"CUP_Mine_M",
//------------------------------------------------------------------
//------------------------------------------------------------------
//
//						Medical
//
//------------------------------------------------------------------
//------------------------------------------------------------------
	"ACE_adenosine",
	"ACE_bodyBag",
	"ACE_epinephrine",
	"ACE_salineIV",
	"ACE_surgicalKit",
	"kat_IV_16",
	"kat_accuvac",
	"kat_X_AED",
	"kat_amiodarone",
	"kat_Carbonate",
	"kat_atropine",
	"kat_AED",
	"kat_BVM",
	"kat_Caffeine",
	"kat_EACA",
	"kat_IO_FAST",
	"kat_fentanyl",
	"kat_ketamine",
	"kat_larynx",
	"kat_naloxone",
	"kat_nitroglycerin",
	"kat_Painkiller",
	"kat_Penthrox",
	"kat_pocketBVM",
	"kat_oxygenTank_150",
	"kat_oxygenTank_300",
	"kat_Pulseoximeter",
	"kat_TXA",
	"kat_stethoscope",
	"kat_ncdKit",
//------------------------------------------------------------------
//------------------------------------------------------------------
//
//						Misc 1
//
//------------------------------------------------------------------
//------------------------------------------------------------------
	"ToolKit",
	"ACE_artilleryTable",
	"ACE_ATragMX",
	"ACE_DefusalKit",
	"ACE_Fortify",
	"ACE_HuntIR_monitor",
	"ACE_Kestrel4500",
	"ACE_Clacker",
	"ACE_M26_Clacker",
	"ACE_PlottingBoard",
	"ACE_RangeCard",
	"ACE_SpottingScope",
	"ACE_Tripod",
	"Attachable_Helistretcher",
//------------------------------------------------------------------
//------------------------------------------------------------------
//
//						Misc 2
//
//------------------------------------------------------------------
//------------------------------------------------------------------
	"ace_marker_flags_black",
	"ace_marker_flags_blue",
	"ace_marker_flags_black",
	"ace_marker_flags_orange",
	"ace_marker_flags_purple",
	"ace_marker_flags_red",
	"ace_marker_flags_white",
	"ace_marker_flags_yellow",
	"ACE_rope12",
	"ACE_rope15",
	"ACE_rope15",
	"ACE_rope18",
	"ACE_rope27",
	"ACE_rope36",
	"ACE_SpareBarrel",
	"ACE_SpraypaintBlack",
	"ACE_SpraypaintBlue",
	"ACE_SpraypaintGreen",
	"ACE_SpraypaintRed",
	"ACE_SpraypaintWhite",
	"ACE_SpraypaintYellow",
	"ACE_UAVBattery",
	"kat_gasmaskFilter",
	"crowsew_tfar_icom",
	"crowsew_ctrack",
	"kat_sealant"
];
