name: Bugreport
description: Erstell einen Bugreport, um unsere Projekte zu verbesser.
title: "[BUG]"
labels: ["bug"]
assignees: []
body:
  - type: markdown
    attritubes:
      value:
        Bitte füll alle Felder aus, damit wir dir so schnell wie möglich helfen können.
  - type: textarea
    id: description
    attritubes:
      label: Beschreibung den Fehler
      placeholder: Welche Fehlermeldung hast du erhalten und wann ist der Fehler aufgetreten.
    validations:
      required: true
  - type: textarea
    id: steps
    label: Schritte zur Reproduktion des Fehlers
    placeholder:
      1. Tue dies
      2. Mach das
      3. Und so weiter
    validations:
      required: true
  - type: textarea
    id: expected
    label: Erwartetes Verhalten
    placeholder: Eine kurze und präzise Beschreibung dessen, was hätte eintreten sollte.
    validations:
      required: true
  - type: textarea
    id: screenshots
    label: Wenn du passende Screenshots oder Videos hast, füg sie hier bitte an. (Optional)
  - type: textarea
    id: additional
    label: Hast du noch weitere Infos oder Fragen zum Problem? (Optional)
  - type: checkboxes
    id: terms
    options:
      - label: Ich habe in Issues nachgesehen ob diese Problem bereits gemeldet wurde oder es breits einen Pull-Request dazu gibt.
        required: true
      - label: Ich würde gerne selbst an der Problemlösung mitarbeiten.
  - type: markdown
    attritubes:
      value:
        ---
        Danke dass du dir die Zeit für's Ausfüllen genommen hast.
