[
    "Sierra Typ 9 - Ausrüstung",
    "Land_PlasticCase_01_large_black_F",
    ["ACE_NVG_Gen4_Black_WP", 8],
    ["SmokeShell", 8],
    ["SmokeShellGreen", 8],
    ["SmokeShellRed", 8],
    ["SmokeShellPurple", 4],
    ["CUP_HandGrenade_M67", 8],
    ["tsp_flashbang_m84", 24],
    ["ACE_IR_Strobe_Item", 8],
    ["B_IR_Grenade", 8],
    ["ACE_HandFlare_Red", 4],
    ["ACE_HandFlare_Green", 4],
    ["ACE_CableTie", 16],
    ["ACE_EarPlugs", 8],
    ["ACE_EntrenchingTool",1],
    ["ACE_wirecutter",1],
    ["kat_Caffeine", 8],
    ["ACE_elasticBandage", 60],
    ["ACE_packingBandage", 60],
    ["ACE_epinephrine", 16],
    ["ACE_morphine", 16],
    ["ACE_salineIV_500", 20],
    ["ACE_splint", 16],
    ["ACE_tourniquet", 16],
    ["kat_chestSeal", 16],
    ["kat_EACA", 16],
    ["kat_TXA", 16],
    ["kat_IO_FAST", 16],
    ["kat_IV_16", 16],
    ["kat_nitroglycerin", 16],
    ["kat_ncdKit", 20],
    ["kat_stethoscope", 2]
];