# This workflow auto assigns PRs to teams

name: PR assignment

on:
    pull_request:
        types: [opened, edited, synchronize, reopened]

jobs:
    auto-assign:
        runs-on: ubuntu-latest
        permissions:
            issues: write
        steps:
            - name: 'Auto-assign PR'
              uses: pozil/auto-assign-issue@v2
              with:
                  repo-token: ${{ secrets.GR_MM_TOKEN }}
                  teams: mission-makers-dev
                  numOfAssignee: 1
                  abortIfPreviousAssignees: true
                  allowSelfAssign: false
