name: CBA Config Linter

on:
  pull_request_target:
    # branches: [ main ]

jobs:
  cba-linter:
    name: CBA Config Linter
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout code
        id: checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
          
      - name: Set up Python
        id: python-setup
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Set up reviewdog
        id: reviewdog-setup
        uses: reviewdog/action-setup@e04ffabe3898a0af8d0fb1af00c188831c4b5893 # v1.3.2
        with:
          reviewdog_version: latest

      - name: Run linter and report results
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ github.token }}
        run: |
          # Run linter with debug output
          python3 tools/python/cba_linter.py cba_configs/ > lint_results.rdjsonl 2> debug.log
          
          # Show debug output
          echo "=== DEBUG LOG ==="
          cat debug.log
          
          # Show lint results
          echo "=== LINT RESULTS ==="
          cat lint_results.rdjsonl
          
          # Report results
          reviewdog -f=rdjsonl \
            -name="CBA Config Linter" \
            -reporter=github-pr-review \
            -filter-mode=nofilter \
            -fail-level=error \
            < lint_results.rdjsonl
