name: CBA Config Linter

on:
  pull_request_target:
    # branches: [ main ]

jobs:
  cba-linter:
    name: CBA Config Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up reviewdog
        uses: reviewdog/action-setup@e04ffabe3898a0af8d0fb1af00c188831c4b5893 # v1.3.2
        with:
          reviewdog_version: latest

      - name: Run Python linter
        run: |
          # Your existing python linting command
          python3 tools/python/cba_linter.py configs/ | \
          reviewdog -f=rdjsonl \
            -name="CBA Config Linter" \
            -reporter=github-pr-review \
            -filter-mode=added \
            -fail-on-error=true \
            -level=error
