name: CBA Config Linter

on:
  pull_request_target:
    # branches: [ main ]

jobs:
  cba-linter:
    name: CBA Config Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Set up reviewdog
        uses: reviewdog/action-setup@e04ffabe3898a0af8d0fb1af00c188831c4b5893 # v1.3.2
        with:
          reviewdog_version: latest

      - name: Run linter and report results
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ github.token }}
        run: |
          # Generate lint results in rdjsonl format
          python3 tools/python/cba_linter.py configs/ > lint_results.rdjsonl
        
          # Report results using reviewdog
          reviewdog -f=rdjsonl \
            -name="CBA Config Linter" \
            -reporter=github-pr-review \
            -filter-mode=added \
            -fail-level=error \
            -level=warning \
            < lint_results.rdjsonl
