name: Auto approve

on:
  workflow_dispatch:
    inputs: 
      pullRequestNumber:
        description: Pull request number to auto-approve
        required: false

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    if: github.actor == 'Cesrap'
    steps:
    - uses: hmarr/auto-approve-action@v4
      with:
        pull-request-number: ${{ github.event.inputs.pullRequestNumber }}
        review-message: "Auto approved CBA-Config-Update"
