name: Discord Release Notification
on:
  release:
    types: [published]

jobs:
  github-releases-to-discord:
    runs-on: ubuntu-latest
    steps:
      - uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.WEBHOOK_URL }}
          nodetail: true
          title: "New version of `software` is ready!"
          description: |
            Version `${{ github.event.release.tag_name }}`
            Click [here](${{ github.event.release.html_url }}) to download!
          color: 0xff91a4

