name: Determining touched Filepaths
on:
    pull_request_target:
        branches:
          - main
        types: [opened, edited, synchronize, reopened]
jobs:
  # JOB to run change detection
  changes:
    runs-on: ubuntu-latest
    # Required permissions
    permissions:
      pull-requests: read
    # Set job outputs to values from filter step
    outputs:
      cba: ${{ steps.filter.outputs.cba }}
      template: ${{ steps.filter.outputs.template }}
      workflows: ${{ steps.filter.outputs.workflows }}
    steps:
    # For pull requests it's not necessary to checkout the code
    - uses: dorny/paths-filter@v3
      id: filter
      with:
        token: ${{ secrets.GR_MM_TOKEN }}
        base: 'main'
        filters: |
          cba:
            - 'cba_configs/**'
          template:
            - '!cba_configs/**'
            - '!.github/**'
          workflows:
            - '.github/**'
        predicate-quantifier: 'every'

  # JOB to build and test backend code
  cba:
    needs: changes
    if: ${{ needs.changes.outputs.cba == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Auto Approve
        if: ${{github.actor == 'Cesrap' }}
        uses: hmarr/auto-approve-action@v4
        with:
            review-message: "Auto approved CBA-Config-Update"

      - name: 'Auto-assign PR'
        if: ${{github.actor != 'Cesrap' }}
        uses: pozil/auto-assign-issue@v2
        with:
            repo-token: ${{ secrets.GR_MM_TOKEN }}
            teams: mission-makers-dev
            numOfAssignee: 1
            abortIfPreviousAssignees: true
            allowSelfAssign: false

  template:
    needs: changes
    if: ${{ needs.changes.outputs.template == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: 'Auto-assign PR'
        uses: pozil/auto-assign-issue@v2
        with:
            repo-token: ${{ secrets.GR_MM_TOKEN }}
            teams: mission-makers-dev
            numOfAssignee: 1
            abortIfPreviousAssignees: true
            allowSelfAssign: false

  workflows:
    needs: changes
    if: ${{ needs.changes.outputs.workflows == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Auto Approve
        if: ${{github.actor == 'ItsGiantCookie' || github.actor == 'HendrikTank' }}
        uses: hmarr/auto-approve-action@v4
        with:
            review-message: "Auto approved Workflow-Update"


      - name: 'Auto-assign PR'
        if: ${{github.actor != 'ItsGiantCookie' && github.actor != 'HendrikTank' }}
        uses: pozil/auto-assign-issue@v2
        with:
            repo-token: ${{ secrets.GR_MM_TOKEN }}
            teams: mission-makers-dev
            numOfAssignee: 1
            abortIfPreviousAssignees: true
            allowSelfAssign: false
  lint:
    needs: template
    runs-on: ubuntu-latest
    steps:
       - name: Checkout
         uses: actions/checkout@v4
       - uses: arma-actions/sqflint@v1.0
         name: Validate with SQFLint with custom arguments
         with:
            args: --directory co79_GerRng_Zug_3_0.VR
